name: Production CI/CD

on:
  push:
    branches: [master]

jobs:
  pull-project-files:
    runs-on: [self-hosted, production]    
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  fetch-env-file:
    runs-on: [self-hosted, production]
    needs: pull-project-files
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Get .env file
        run: cp -r /root/env_files/chitchat/.env.production /root/actions_runners/chitchat-action-runner/_work/react-chat-app-frontend/react-chat-app-frontend/

  make-build:
    runs-on: [self-hosted, production]    
    needs: fetch-env-file
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --save
      - name: Clear cache
        run: npm cache clean --force
      - run: npm run build
      - name: Remove previous build
        run: if [ -d "/root/frontend_applications/chitchat/" ]; then rm -r /root/frontend_applications/chitchat/*; fi
      - name: Move new build
        run: ls && cd build && mv -f * /root/frontend_applications/chitchat/
      - name: Remove project files
        run: rm -r /root/actions_runners/chitchat-action-runner/_work/react-chat-app-frontend/react-chat-app-frontend
